version: "3.8"
services:
  db:
    image: postgres:16
    container_name: odoo19_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo19
      - POSTGRES_PASSWORD=Somya@123
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    container_name: odoo19_app
    depends_on:
      - db
    ports:
      - "8012:8069"
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo19
      - PASSWORD=Somya@123
    command : ["odoo","-c","/etc/odoo.conf","-d","test_db_1"]
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo.conf
    restart: unless-stopped

volumes:
  db_data:
  odoo_data:
